# Generated by Django 2.0.2 on 2018-03-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
